### ISSUE TITLE
Bug with using mentat from an internal directory

### ISSUE THREAD

**Issue by swinglejohn** [AbanteAI/mentat#176]
I am getting an error when I try to run mentat from an internal directory. I'll include the error message I get from running it in mentat/mentat. I get this error from running it both as installed via pip or just `p -m mentat`. My main up to date when I tried this. @biobootloader has had trouble reproducing the issue so if anybody else manages that would be good to know. I am running popOS (Ubuntu).

Error:
`(venv) [username]@[hostname]:~/[...]/project$ python -m mentat broadcast.py 

Code Context:
  Directory: /home/[...]/[...]/mentat
  Diff: 
  Included files:
    mentat
    └── mentat
        └── broadcast.py
  CodeMaps: Enabled
  Auto-tokens: Model max (default)
Prompt and included files token count: 2275 / 8192
Type 'q' or use Ctrl-C to quit at any time.
What can I do for you?
>>> Explain this file to me                                                                                                                                                                    
2023-10-18 10:10:07,769 - ERROR - Main task for Session([session_id]) threw an exception
Traceback (most recent call last):
  File "/home/[...]/[...]/mentat/mentat/session.py", line 150, in run_main
    await self._main()
  File "/home/[...]/[...]/mentat/mentat/session.py", line 118, in _main
    file_edits = await conversation.get_model_response()
  File "/home/[...]/[...]/mentat/mentat/conversation.py", line 175, in get_model_response
    code_message = await code_context.get_code_message(
  File "/home/[...]/[...]/mentat/mentat/code_context.py", line 167, in get_code_message
    self._code_message = await self._get_code_message(prompt, model, max_tokens)
  File "/home/[...]/[...]/mentat/mentat/code_context.py", line 199, in _get_code_message
    self.features = await self._get_auto_features(
  File "/home/[...]/[...]/mentat/mentat/code_context.py", line 249, in _get_auto_features
    or not is_file_text_encoded(path)
  File "/home/[...]/[...]/mentat/mentat/include_files.py", line 39, in is_file_text_encoded
    with open(file_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mentat/utils.py'
`

**Comment by gssakash-SxT** [comment]
I assume this is because of the outer directory being the same as the inner directory. Leave the inner ``mentat`` directory as it but rename the outer directory to something else and see if that fixes your problem @swinglejohn

**Comment by gssakash-SxT** [comment]
Can you give me a tree of your current project? Because I have some extra files and a mentat directory in my project as well and I've never had an error like this. I'm importing the mentat client and using it for a bunch of stuff and I think I have a similar folder structure to you
